/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emmastewartgui;

/**
 *
 * @author Emma
 */
public class ESGuiPersonalInfo extends javax.swing.JDialog {

    /**
     * Creates new form ESGuiPersonalInfo
     */
    public ESGuiPersonalInfo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPersonalBests = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbl200Back = new javax.swing.JPanel();
        txtfld200IM = new javax.swing.JTextField();
        lbl50Back = new javax.swing.JLabel();
        lbl50Fly = new javax.swing.JLabel();
        txtfld400IM = new javax.swing.JTextField();
        lbl50Free = new javax.swing.JLabel();
        lblNamePB4 = new javax.swing.JLabel();
        txtfld800Free = new javax.swing.JTextField();
        textfld100IM = new javax.swing.JTextField();
        lbl200Fly = new javax.swing.JLabel();
        lbl100Back = new javax.swing.JLabel();
        lbl100Breast = new javax.swing.JLabel();
        lbl100Free = new javax.swing.JLabel();
        lbl100Fly = new javax.swing.JLabel();
        lblNamePB10 = new javax.swing.JLabel();
        lbl200Breast = new javax.swing.JLabel();
        lbl200Free = new javax.swing.JLabel();
        lbl200IM = new javax.swing.JLabel();
        lbl100IM = new javax.swing.JLabel();
        lbl400Free = new javax.swing.JLabel();
        lbl400IM = new javax.swing.JLabel();
        lbl1000Free = new javax.swing.JLabel();
        lbl800Free = new javax.swing.JLabel();
        txtfld1000Free = new javax.swing.JTextField();
        txtfld400Free = new javax.swing.JTextField();
        txtfld200Free = new javax.swing.JTextField();
        txtfld200Breast = new javax.swing.JTextField();
        txtfld200Back = new javax.swing.JTextField();
        txtfld200Fly = new javax.swing.JTextField();
        txtfld100Free = new javax.swing.JTextField();
        txtfld100Breast = new javax.swing.JTextField();
        txtfld100Back = new javax.swing.JTextField();
        txtfld100Fly = new javax.swing.JTextField();
        txtfld50Free = new javax.swing.JTextField();
        txtfld50Breast = new javax.swing.JTextField();
        txtfld50Back = new javax.swing.JTextField();
        txtfld50Fly = new javax.swing.JTextField();
        btnSavePB = new javax.swing.JButton();
        lblProfile = new javax.swing.JLabel();
        btnDonePB = new javax.swing.JButton();
        lblNamePB = new javax.swing.JLabel();
        txtfldName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblPersonalBests.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblPersonalBests.setText("Personal Bests");

        txtfld200IM.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld200IM.setText("[insert time]");
        txtfld200IM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld200IMActionPerformed(evt);
            }
        });

        lbl50Back.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl50Back.setText("50m Backstroke:");

        lbl50Fly.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl50Fly.setText("50m Butterfly:");

        txtfld400IM.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld400IM.setText("[insert time]");
        txtfld400IM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld400IMActionPerformed(evt);
            }
        });

        lbl50Free.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl50Free.setText("50m Freestyle:");

        lblNamePB4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNamePB4.setText("50m Breaststroke:");

        txtfld800Free.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld800Free.setText("[insert time]");
        txtfld800Free.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld800FreeActionPerformed(evt);
            }
        });

        textfld100IM.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        textfld100IM.setText("[insert time]");
        textfld100IM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfld100IMActionPerformed(evt);
            }
        });

        lbl200Fly.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl200Fly.setText("200m Butterfly:");

        lbl100Back.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl100Back.setText("100m Backstroke:");

        lbl100Breast.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl100Breast.setText("100m Breaststroke:");

        lbl100Free.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl100Free.setText("100m Freestyle:");

        lbl100Fly.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl100Fly.setText("100m Butterfly:");

        lblNamePB10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNamePB10.setText("200m Backstroke:");

        lbl200Breast.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl200Breast.setText("200m Breaststroke:");

        lbl200Free.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl200Free.setText("200m Freestyle:");

        lbl200IM.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl200IM.setText("200m Individual Medley:");

        lbl100IM.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl100IM.setText("100m Individual Medley:");

        lbl400Free.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl400Free.setText("400m Freestyle:");

        lbl400IM.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl400IM.setText("400m Individual Medley:");

        lbl1000Free.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl1000Free.setText("1000m Freestyle:");

        lbl800Free.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl800Free.setText("800m Freestyle:");

        txtfld1000Free.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld1000Free.setText("[insert time]");
        txtfld1000Free.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld1000FreeActionPerformed(evt);
            }
        });

        txtfld400Free.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld400Free.setText("[insert time]");
        txtfld400Free.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld400FreeActionPerformed(evt);
            }
        });

        txtfld200Free.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld200Free.setText("[insert time]");
        txtfld200Free.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld200FreeActionPerformed(evt);
            }
        });

        txtfld200Breast.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld200Breast.setText("[insert time]");
        txtfld200Breast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld200BreastActionPerformed(evt);
            }
        });

        txtfld200Back.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld200Back.setText("[insert time]");
        txtfld200Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld200BackActionPerformed(evt);
            }
        });

        txtfld200Fly.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld200Fly.setText("[insert time]");
        txtfld200Fly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld200FlyActionPerformed(evt);
            }
        });

        txtfld100Free.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld100Free.setText("[insert time]");
        txtfld100Free.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld100FreeActionPerformed(evt);
            }
        });

        txtfld100Breast.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld100Breast.setText("[insert time]");
        txtfld100Breast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld100BreastActionPerformed(evt);
            }
        });

        txtfld100Back.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld100Back.setText("[insert time]");
        txtfld100Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld100BackActionPerformed(evt);
            }
        });

        txtfld100Fly.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld100Fly.setText("[insert time]");
        txtfld100Fly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld100FlyActionPerformed(evt);
            }
        });

        txtfld50Free.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld50Free.setText("[insert time]");
        txtfld50Free.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld50FreeActionPerformed(evt);
            }
        });

        txtfld50Breast.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld50Breast.setText("[insert time]");
        txtfld50Breast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld50BreastActionPerformed(evt);
            }
        });

        txtfld50Back.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld50Back.setText("[insert time]");
        txtfld50Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld50BackActionPerformed(evt);
            }
        });

        txtfld50Fly.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtfld50Fly.setText("[insert time]");
        txtfld50Fly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld50FlyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lbl200BackLayout = new javax.swing.GroupLayout(lbl200Back);
        lbl200Back.setLayout(lbl200BackLayout);
        lbl200BackLayout.setHorizontalGroup(
            lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl200BackLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lbl200BackLayout.createSequentialGroup()
                            .addComponent(lbl400Free)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtfld400Free, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lbl200BackLayout.createSequentialGroup()
                            .addComponent(lbl1000Free)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtfld1000Free, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lbl200BackLayout.createSequentialGroup()
                            .addComponent(lbl800Free)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtfld800Free, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lbl200BackLayout.createSequentialGroup()
                            .addComponent(lbl400IM)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtfld400IM, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(lbl200BackLayout.createSequentialGroup()
                        .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl200IM)
                            .addComponent(lbl200Free)
                            .addComponent(lbl200Breast)
                            .addComponent(lblNamePB10)
                            .addComponent(lbl200Fly))
                        .addGap(18, 18, 18)
                        .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfld200Fly, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfld200Back, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfld200Breast, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfld200Free, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfld200IM, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(lbl200BackLayout.createSequentialGroup()
                        .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl100IM)
                            .addComponent(lbl100Free)
                            .addComponent(lbl100Breast)
                            .addComponent(lbl100Back)
                            .addComponent(lbl100Fly)
                            .addComponent(lbl50Free)
                            .addComponent(lblNamePB4)
                            .addComponent(lbl50Back)
                            .addComponent(lbl50Fly))
                        .addGap(18, 18, 18)
                        .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfld50Fly, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfld50Back, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfld50Breast, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfld50Free, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfld100Fly, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfld100Back, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfld100Breast, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfld100Free, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfld100IM, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(599, Short.MAX_VALUE))
        );
        lbl200BackLayout.setVerticalGroup(
            lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl200BackLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl50Fly, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld50Fly))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl50Back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld50Back))
                .addGap(11, 11, 11)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamePB4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld50Breast))
                .addGap(13, 13, 13)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl50Free, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld50Free))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl100Fly, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld100Fly))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl100Back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld100Back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl100Breast, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld100Breast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl100Free, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld100Free))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl100IM, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfld100IM))
                .addGap(70, 70, 70)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl200Fly, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld200Fly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamePB10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld200Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl200Breast, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld200Breast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl200Free, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld200Free, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl200IM, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld200IM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl400Free, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld400Free, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl400IM, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld400IM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl800Free)
                    .addComponent(txtfld800Free, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(lbl200BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1000Free, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld1000Free, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(lbl200Back);

        btnSavePB.setText("SAVE");
        btnSavePB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePBActionPerformed(evt);
            }
        });

        lblProfile.setFont(new java.awt.Font("Tahoma", 0, 54)); // NOI18N
        lblProfile.setText("Profile");

        btnDonePB.setText("DONE");

        lblNamePB.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNamePB.setText("Name:");

        txtfldName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtfldName.setText("[insert name]");
        txtfldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1373, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(lblNamePB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtfldName, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblProfile))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSavePB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDonePB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPersonalBests, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(495, 1013, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDonePB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSavePB, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNamePB, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfldName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(14, 14, 14)
                    .addComponent(lblPersonalBests, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(1, 1, 1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfld200IMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld200IMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld200IMActionPerformed

    private void txtfld400IMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld400IMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld400IMActionPerformed

    private void txtfld800FreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld800FreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld800FreeActionPerformed

    private void textfld100IMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfld100IMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfld100IMActionPerformed

    private void txtfld1000FreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld1000FreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld1000FreeActionPerformed

    private void txtfld400FreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld400FreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld400FreeActionPerformed

    private void txtfld200FreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld200FreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld200FreeActionPerformed

    private void txtfld200BreastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld200BreastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld200BreastActionPerformed

    private void txtfld200BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld200BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld200BackActionPerformed

    private void txtfld200FlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld200FlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld200FlyActionPerformed

    private void txtfld100FreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld100FreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld100FreeActionPerformed

    private void txtfld100BreastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld100BreastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld100BreastActionPerformed

    private void txtfld100BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld100BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld100BackActionPerformed

    private void txtfld100FlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld100FlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld100FlyActionPerformed

    private void txtfld50FreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld50FreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld50FreeActionPerformed

    private void txtfld50BreastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld50BreastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld50BreastActionPerformed

    private void txtfld50BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld50BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld50BackActionPerformed

    private void txtfld50FlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld50FlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld50FlyActionPerformed

    private void btnSavePBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSavePBActionPerformed

    private void txtfldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ESGuiPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ESGuiPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ESGuiPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ESGuiPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ESGuiPersonalInfo dialog = new ESGuiPersonalInfo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonePB;
    private javax.swing.JButton btnSavePB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1000Free;
    private javax.swing.JLabel lbl100Back;
    private javax.swing.JLabel lbl100Breast;
    private javax.swing.JLabel lbl100Fly;
    private javax.swing.JLabel lbl100Free;
    private javax.swing.JLabel lbl100IM;
    private javax.swing.JPanel lbl200Back;
    private javax.swing.JLabel lbl200Breast;
    private javax.swing.JLabel lbl200Fly;
    private javax.swing.JLabel lbl200Free;
    private javax.swing.JLabel lbl200IM;
    private javax.swing.JLabel lbl400Free;
    private javax.swing.JLabel lbl400IM;
    private javax.swing.JLabel lbl50Back;
    private javax.swing.JLabel lbl50Fly;
    private javax.swing.JLabel lbl50Free;
    private javax.swing.JLabel lbl800Free;
    private javax.swing.JLabel lblNamePB;
    private javax.swing.JLabel lblNamePB10;
    private javax.swing.JLabel lblNamePB4;
    private javax.swing.JLabel lblPersonalBests;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JTextField textfld100IM;
    private javax.swing.JTextField txtfld1000Free;
    private javax.swing.JTextField txtfld100Back;
    private javax.swing.JTextField txtfld100Breast;
    private javax.swing.JTextField txtfld100Fly;
    private javax.swing.JTextField txtfld100Free;
    private javax.swing.JTextField txtfld200Back;
    private javax.swing.JTextField txtfld200Breast;
    private javax.swing.JTextField txtfld200Fly;
    private javax.swing.JTextField txtfld200Free;
    private javax.swing.JTextField txtfld200IM;
    private javax.swing.JTextField txtfld400Free;
    private javax.swing.JTextField txtfld400IM;
    private javax.swing.JTextField txtfld50Back;
    private javax.swing.JTextField txtfld50Breast;
    private javax.swing.JTextField txtfld50Fly;
    private javax.swing.JTextField txtfld50Free;
    private javax.swing.JTextField txtfld800Free;
    private javax.swing.JTextField txtfldName;
    // End of variables declaration//GEN-END:variables
}
